### PR TITLE
Cherry-pick: ICU-21041 Fix fuzzer memory read error.

### PR DESCRIPTION
**Pull request by daniel-ju**
## Summary
This change cherry-picks an upstream fix for a null-dereference error.

Upstream ticket: https://unicode-org.atlassian.net/browse/ICU-21041
Upstream PR: https://github.com/unicode-org/icu/pull/1622

Note: The upstream change modifies 3 files, but only 2 files are modified here as we don't include the `.cpyskip.txt` file in MS-ICU (used for syntax highlighting on GitHub).

## PR Checklist
* [x] I have verified that my change is specific to this fork and cannot be made upstream.
* [x] I am making a maintenance related change.
* [ ] I am making a change that is related to usage internal to Microsoft.
* [ ] I am making a change that is related to the Windows OS build of ICU.
* [x] CLA signed. If not, please see [here](https://cla.opensource.microsoft.com/microsoft/icu) to sign the CLA.

### CODE REVIEW

**Review by erik0686 — APPROVED** [review]

**Comment by jefgen** [comment]
Thanks @daniel-ju!

Would you mind also adding a note to the [changelog.md](https://github.com/microsoft/icu/blob/master/changelog.md#changes-cherry-picked-from-upstream-ticketsprs) file as well under the section "Changes cherry-picked from upstream tickets/PRs"? :)
Thank you!

**Comment by daniel-ju** [comment]
> Thanks @daniel-ju!
> 
> Would you mind also adding a note to the [changelog.md](https://github.com/microsoft/icu/blob/master/changelog.md#changes-cherry-picked-from-upstream-ticketsprs) file as well under the section "Changes cherry-picked from upstream tickets/PRs"? :)
> 
> Also, I think we'll probably want to do the same in PR #83 as well.
> 
> Thank you!

@jefgen I wasn't sure if we wanted to keep the cherry-pick on its own and update the changelog file later. I guess it doesn't make it any cleaner or add much value though. I can update the changelog here, thanks! :)

**Comment by jefgen** [comment]
> I wasn't sure if we wanted to keep the cherry-pick on its own and update the changelog file later. I guess it doesn't make it any cleaner or add much value though. I can update the changelog here, thanks! :)

Ah, I was thinking that it would save you the trouble from having to make another separate PR -- but if you'd prefer to have the changelog.md be done by itself that is fine with me as well. :)

**Review by jefgen — APPROVED** [review]
lgtm, thank you!

**Pull request merged**
