### PR TITLE
Pick up tzdata 2021a updates

### PR DESCRIPTION
**Pull request by daniel-ju**
## Summary
This updates to the latest tzdata taken from https://github.com/unicode-org/icu-data/tree/master/tzdata/icunew/2021a/44.
I also ran our internal script on top of these files to apply our time zone overrides for sensitive terms.

## PR Checklist
* [x] I have verified that my change is specific to this fork and cannot be made upstream.
* [x] I am making a maintenance related change.
* [x] I am making a change that is related to usage internal to Microsoft.
* [ ] I am making a change that is related to the Windows OS build of ICU.
* [x] CLA signed. If not, please see [here](https://cla.opensource.microsoft.com/microsoft/icu) to sign the CLA.

### CODE REVIEW

**Review by axelandrejs — APPROVED** [review]

**Comment by jefgen** [comment]
Thanks Daniel! 

Hmm, it looks like there is a test failure in the CI builds:

```
 -------------
 | ***     FAILING TEST SUMMARY FOR:              intltest  
          TestCanonicalID
       TimeZoneTest
    format
 | *** END FAILING TEST SUMMARY FOR:              intltest
 ---------------
```

Investigating a bit... since this is updating the tzdata from `2020d` to `2021a`, I think there is a fix that was made for the tzdata 2020f update that we'll also want to pick up as well.

Here is a link to the test code fix in the ICU4C test code:
https://github.com/unicode-org/icu/commit/25eb1510ec4e536fe0d0d1024b3ce71819510d0a#diff-6d245614a81d5ad55dc7abe04b37a59d968ad805260d36ac20e0af728e5a3efe
It changes the expected value for: from `Australia/Currie` to `Australia/Hobart`.

(I think we should likely just take the change without a patch file, since it will be included in newer versions of ICU).

Would you mind picking up the text fix as well so the CI builds are clean?
Thank you!

**Comment by jefgen** [comment]
Ah, I wonder if maybe I should wait on PR #75 for this PR, and then we can include the tzdata 2021a update as well.

**Review by jefgen — CHANGES_REQUESTED** [review]
Thanks @daniel-ju, the change looks pretty good!

I think there is just one additional test fix needed.
Also, would you mind also updating the `changelog.md` file to add a note about picking up the tzdata 2021a?

Thank you!

**Comment by daniel-ju** [comment]
Thanks @jefgen for the pointer to the upstream fix! I've updated/fixed the tests so that the checks are clean, and added a note to the changelog so that we can bundle this update with the version bump. :)

**Review by erik0686 — APPROVED** [review]

**Review by jefgen — APPROVED** [review]
lgtm, thanks!

For merging: please use a squash merge.

**Pull request merged**
