### PR TITLE
Update ff-Latn-MR region name

### PR DESCRIPTION
**Pull request by daniel-ju**
## Summary
This removes the PS country/region name data for ff_Latn_MR due to the data not being in Latin script.

## PR Checklist
* [x] I have verified that my change is specific to this fork and cannot be made upstream.
* [ ] I am making a maintenance related change.
* [x] I am making a change that is related to usage internal to Microsoft.
* [ ] I am making a change that is related to the Windows OS build of ICU.
* [x] CLA signed. If not, please see [here](https://cla.opensource.microsoft.com/microsoft/icu) to sign the CLA.

### CODE REVIEW

**Review by axelandrejs — APPROVED** [review]

**Review by jefgen — APPROVED** [review]

**Review by erik0686 — APPROVED** [review]

**Comment by jefgen** [comment]
Regarding the failing CI builds: It looks like the issue is due to the outdated guava version.
The dependabot created a PR here to update it: #87 

I think if you rebase on-top of the most recent commit, then the CI build should be happier. :)

**Review by jefgen — APPROVED** [review]
Thanks @daniel-ju :)

**Comment by jefgen** [comment]
Hmm.. it looks like the change in PR #87 might not have been enough perhaps..
It bumped the `guava` version from 27.1 to 29.0. However, now the CG task is complaining that version 29 has issues.

But this is somewhat confusing as the report on the GitHub page says:
> No security update is needed as com.google.guava:guava is no longer vulnerable

Yet, it also says that we should upgrade to version 30.0:
> Upgrade com.google.guava:guava to version 30.0-jre or later. For example:

Since the CG task is still failing, I think we likely do need to update it. It's too bad the dependabot PR updated to a vulnerable version... 

However, since this only effects the CLDR-to-ICU data build tool, which only runs on a dev machine, I think it would be fine to bypass the check on this PR, and we can fix this later.

**Comment by daniel-ju** [comment]
Thanks @jefgen! I'll go ahead and bypass the check for now, and try to update to 30.0 in a separate PR then.

**Pull request merged**
