### PR TITLE
[ICU 68.1 Update] Regenerate ICU data using CLDR-MS + MS-ICU locales, apply test patches

### PR DESCRIPTION
**Pull request by jefgen**
## Summary
This is part 7 of N for updating to ICU 68.1.

This change regenerates the MS-ICU data files using the CLDR-MS v38 data from MSCodeHub.

## PR Checklist
* [x] I have verified that my change is specific to this fork and cannot be made upstream.
* [ ] I am making a maintenance related change.
* [ ] I am making a change that is related to usage internal to Microsoft.
* [ ] I am making a change that is related to the Windows OS build of ICU.
* [x] CLA signed. If not, please see [here](https://cla.opensource.microsoft.com/microsoft/icu) to sign the CLA.

## Detailed Description
This change regenerates the MS-ICU data files using the CLDR-MS v38 data from MSCodeHub along with the modified set of locales for MS-ICU (using the updated `build-icu-data.xml` file).
It also applies changes to the ICU tests in order get all tests passing using the updated data, and regenerates the patch files.

Regenerating the patch files was necessary due to the migration to GitHub from MSCodeHub, and also as some of the changes were slightly different now that the locale sa has moved from seed to main.

For the `build-icu-data.xml` file, I used the configuration from MS-ICU 67, and then hand-carried the changes forward on to ICU 68 and merged in the upstream changes.

Comparing ICU 67 to ICU 68, these were the upstream changes:
- Primary Locale ID changes:
  - Added: doi, sa
  - Removed: nds

- Collation ID changes:
  - Added: br, sa

We already add the locale `sa` in MS-ICU, so the new changes I made (on top of carrying forward from MS-ICU 67) were adding back `nds`, and adding the new locales `doi`/`doi_IN`, and then adding the new collation locales `br` and `sa`.

Regarding the new doi/doi_IN locale: The Dogri language (`doi`) does not have a suppress-script registered in the [IANA Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), so we need to use the locale name of `doi-Deva-IN` for NLS -- as it requires stable locale names over time.

I added a new alias to MS-ICU for it, so that we can round-trip the locale name between MS-ICU and NLS:

``` xml
<!-- Dogri does not have a suppress script. doi_Deva_IN in the locale name in NLS while doi_IN is the locale name in ICU. -->
<forcedAlias source="doi_Deva_IN" target="doi_IN"/>
```

All of the `.patch` files under `icu-patches` have now been applied. This PR applied the two remaining patches that weren't done in PR #53 since they required updating the data first.

All test now pass with the updated/regenerated data.

### CODE REVIEW

**Comment by daniel-ju** [comment]
CodeFlow seems unable to load all the file changes for me, even though they show up on Github :(
image

**Comment by jefgen** [comment]
> CodeFlow seems unable to load all the file changes for me, even though they show up on Github :(

Ugh...  :(

I'm also seeing the same problem on my PC as well, so I don't think it's unique to your setup...
FWIW, this is why I was trying to split things up into smaller, more frequent PRs... but the "rebuild ICU data" step is sort of hard to split up into smaller logical PRs.

I wonder if maybe there's another way to view the diffs...?

Poking around a bit, it seems there's now a GitHub extension for VS Code that can show PRs and their diffs as well:
https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

I was able to get it to load (after some time) this PR and it _seems_ like it loaded all the diffs:
image

You have to click on the various files to see the diffs, but it kinda, sorta works I guess. :)

**Comment by daniel-ju** [comment]
> Poking around a bit, it seems there's now a GitHub extension for VS Code that can show PRs and their diffs as well

Neat! Thanks Jeff!

**Comment by daniel-ju** [comment]
Just to confirm, the nds locale was only removed on the upstream ICU side, but CLDR still has it and we're just adding it back so that MS-ICU still uses the nds locale data from CLDR?

**Comment by daniel-ju** [comment]
> All test now pass with the updated/regenerated data.

Yay! :)

**Comment by jefgen** [comment]
> Just to confirm, the nds locale was only removed on the upstream ICU side, but CLDR still has it and we're just adding it back so that MS-ICU still uses the nds locale data from CLDR?

Right, that's correct.
Upstream CLDR still has the locale `nds` in main: https://github.com/unicode-org/cldr/blob/master/common/main/nds.xml

The discussion on CLDR ticket https://unicode-org.atlassian.net/browse/CLDR-14080 was that for ICU 68 the following changes would occur:

> The new changes that I am planning to add as part of CLDR 38 integration [into ICU] are as follows:
> Add:
> - "Dogri": doi, doi_IN
> - "Sanskrit": sa, sa_IN
>
> Remove uncommon locale with very poor data coverage statistics:
> - "Low German": nds, nds_DE, nds_NL

Since we can't/don't want to remove locales from MS-ICU/CLDR-MS or NLS, I added back `nds` to MS-ICU in the `build-icu-data.xml` config file.

**Review by daniel-ju — APPROVED** [review]
LGTM, thanks! :)

**Pull request merged**
