### PR TITLE
[ICU 68.1 Update] Initial commit of unmodified ICU source code

### PR DESCRIPTION
**Pull request by jefgen**
## Summary
This PR is part 1 of N for updating to ICU 68.1.

This PR is an initial commit of the unmodified ICU source code and data from the upstream `maint/maint-68` branch.

I'm doing this as it's own separate commit and PR in order to make the history cleaner, and to make reviewing subsequent changes easier. Otherwise the diffs would be so massive that GitHub can't even load them.

## PR Checklist
* [x] I have verified that my change is specific to this fork and cannot be made upstream.
* [ ] I am making a maintenance related change.
* [ ] I am making a change that is related to usage internal to Microsoft.
* [ ] I am making a change that is related to the Windows OS build of ICU.
* [x] CLA signed. If not, please see [here](https://cla.opensource.microsoft.com/microsoft/icu) to sign the CLA.

## Detailed Description

ICU 68.1 release notes: http://site.icu-project.org/download/68
CLDR 38: release notes: http://cldr.unicode.org/index/downloads/cldr-38

Note: The upstream `maint/maint-68` branch currently has additional fixes that were not part of the actual ICU 68.1 release.

However, I'm including them in this PR in order to avoid having to separately cherry-pick them later.
The ICU-TC is planning on having a "dot release" for 68 in order to fix issues that were identified after 68.1 was released. This 68.2 version should come out some time in Dec/Jan, and we'll need to update to this later. We can avoid a small bit of churn by pulling in the fixes from the upstream `maint/maint-68` branch now.

I've also been updating/revising the [Updating MS-ICU](https://osgwiki.com/wiki/Updating_MS-ICU) wiki page as I go in order to  make changes due to the GitHub undocking work and other changes.

This PR is going directly into the `master` branch, as we have separate branches for the `maint/maint-64` and `maint/maint-67` versions on GitHub. Once this is merged the `master` branch will no longer be "in sync" with 67.1, and will become a 68.1 "staging" branch. Similarly on the MSCodeHub side, I'll create a versioned branch for the MS-ICU 67.1 version, and then once the git submodule is updated the `master` branch will be the "staging" branch.

Next up will be the update to the CLDR-to-ICU data build tool. After that is the update/removal and application of the various MSFT patch files and version updates. However, they will need to all be regenerated by hand due to the migration to GitHub.

Note: The CI builds for this PR will _fail_ and that is _expected_. I will need to update the CI pipelines later on afterwards, but that needs to be done as a separate commit. For now I will bypass the checks.

### CODE REVIEW

**Review by axelandrejs — APPROVED** [review]

**Review by erik0686 — APPROVED** [review]

**Review by daniel-ju — APPROVED** [review]

**Comment by daniel-ju** [comment]
Thank you for updating the docs as well! :)

**Comment by jefgen** [comment]
> This PR is going directly into the `master` branch, as we have separate branches for the `maint/maint-64` and `maint/maint-67` versions on GitHub. Once this is merged the `master` branch will no longer be "in sync" with 67.1, and will become a 68.1 "staging" branch.
> However, on the MSCodeHub side I plan to create a `icu68-staging` branch instead and make the changes there. Once done then I'll merge to master when finished the on-boarding. (Technically we could do the same and use the `master` branch on MSCodeHub as a staging branch, but historically we've used separate staging branches in MSCodeHub).

Actually, I was thinking about this a bit more, and I think the main reason we had a separate staging branch on the MSCodeHub side last time was because we were working on the ICU 67 update _at the same time_ as the undocking/migration to GitHub.

I think it might actually be simpler to also use the `master` branch in MSCodeHub for the 68.1 ingestion (like on GitHub), as we can create a versioned branch for ICU 67.1 now, and we likely won't be rev'ing it much in the meantime.

**Comment by daniel-ju** [comment]
> I think it might actually be simpler to also use the master branch in MSCodeHub for the 68.1 ingestion (like on GitHub), as we can create a versioned branch for ICU 67.1 now, and we likely won't be rev'ing it much in the meantime.

That sounds logical to me, then we can see the diffs on MS-ICU earlier.

**Comment by jefgen** [comment]
> Thank you for updating the wiki page as well! :)

No problem! Thanks for doing such a great job updating it last time!

> That sounds logical to me, then we can see the diffs on MS-ICU earlier.

Thanks! I'll update the PR description and the wiki page with the new plan. :)

**Pull request merged**
